# These are supported funding model platforms

github: [justAbdulaziz10, gqnxx]

buy_me_a_coffee: https://buymeacoffee.com/iammara
github_sponsor: https://github.com/sponsors/justAbdulaziz10?editing=false&frequency=recurring&preview=true&sponsor=justAbdulaziz10
