version: 2
updates:
  # Python dependencies (backend)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Dart dependencies (Flutter app)
  - package-ecosystem: "pub"
    directory: "/marafinal"
    schedule:
      interval: "weekly"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
