title = "Mara Gitleaks"

[[rules]]
description = "Firebase Private Key"
id = "firebase-private-key"
regex = '''-----BEGIN PRIVATE KEY-----'''
tags = ["key", "firebase"]

[[rules]]
description = "Supabase keys"
id = "supabase-keys"
regex = '''(SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY)\s*=\s*['"][A-Za-z0-9\.\-_]+['"]'''
tags = ["key", "supabase"]

[allowlist]
files = [
  '''^docs/''',
  '''^tests/fixtures/'''
]
