version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mara
      POSTGRES_PASSWORD: mara
      POSTGRES_DB: maradb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mara"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
