version: "3"
tasks:
  dev:
    cmds: ["uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000"]
  test:
    cmds: ["cd backend && pytest -q", "cd marafinal && flutter test"]
  lint:
    cmds: ["cd backend && flake8 .", "cd marafinal && flutter analyze"]
  up:
    cmds: ["docker compose up -d --build"]
  down:
    cmds: ["docker compose down"]
