apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols: { http: {}, grpc: {} }
    exporters:
      logging: {}
      otlp:
        endpoint: "https://otlp.example.com"
        headers: { "x-api-key": "${OTLP_API_KEY}" }
    service:
      pipelines:
        traces: { receivers: [otlp], exporters: [otlp, logging] }
        metrics: { receivers: [otlp], exporters: [otlp, logging] }
