name: SBOM
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  cyclonedx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CycloneDX for Python
        run: |
          pipx install cyclonedx-bom
          cd backend
          pip install -r requirements.txt
          cyclonedx-py --format json -o ../sbom-backend.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: |
            sbom-backend.json
