name: Mark stale issues and PRs
on:
  schedule: [ { cron: "0 2 * * *" } ]
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          stale-issue-message: "This issue has been marked stale due to inactivity."
          stale-pr-message: "This PR has been marked stale due to inactivity."
          exempt-issue-labels: "pinned,security"
          exempt-pr-labels: "pinned,security"
